# Generated by Django 3.2.3 on 2021-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='scheduledItemID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
