# Generated by Django 3.2.3 on 2021-07-05 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomeschoolTool', '0002_alter_scheduleditem_scheduleditemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurrencetype',
            old_name='recurrenceType',
            new_name='recurrenceTypeName',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
