# Generated by Django 3.2.3 on 2021-06-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0002_alter_week_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentID', models.AutoField(default='', primary_key=True, serialize=False)),
                ('studentName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='week',
            name='StudentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentID', to='HomeschoolTool.student'),
        ),
    ]
