# Generated by Django 3.2.3 on 2021-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0003_auto_20210705_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleditem',
            name='fullDay',
            field=models.BooleanField(default=True),
        ),
    ]
