# Generated by Django 3.2.3 on 2021-07-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0004_scheduleditem_fullday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleditem',
            old_name='fullDay',
            new_name='allDay',
        ),
    ]
