# Generated by Django 3.2.3 on 2021-07-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0006_userextended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
