# Generated by Django 3.2.3 on 2021-08-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeschoolTool', '0008_auto_20210807_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleditem',
            old_name='reoccurEnd',
            new_name='recurEnd',
        ),
        migrations.RenameField(
            model_name='scheduleditem',
            old_name='reoccurType',
            new_name='recurType',
        ),
    ]
