# Generated by Django 3.2.3 on 2021-08-09 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomeschoolTool', '0009_auto_20210808_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='classT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeschoolTool.teacherclass'),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='details',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='recurType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeschoolTool.recurrencetype'),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeschoolTool.student'),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
